close all
clear all

%loading various drive cycles involved in the E&EC 4cycle
run('Drive_cycles.m');

%storing at the wheel results for UDDS-505
[UDDS_505_Propulsion_energy,UDDS_505_Braking_energy,...
    UDDS_505_Net_energy,...
    UDDS_505_Avg_positive_power,UDDS_505_Peak_power,...
    UDDS_505_Peak_tractive_force,...
    UDDS_505_Idle_time]=at_the_wheels_results(UDDS_505);

%storing at the wheel results for HWFET
[HWFET_Propulsion_energy,HWFET_Braking_energy,...
    HWFET_Net_energy,...
    HWFET_Avg_positive_power,HWFET_Peak_power,...
    HWFET_Peak_tractive_force,...
    HWFET_Idle_time]=at_the_wheels_results(HWFET);

%storing at the wheel results for US06 City
[US06_city_Propulsion_energy,US06_city_Braking_energy,...
    US06_city_Net_energy,...
    US06_city_Avg_positive_power,US06_city_Peak_power,...
    US06_city_Peak_tractive_force,...
    US06_city_Idle_time]=at_the_wheels_results(US06_city);

%storing at the wheel results for US06 Highway
[US06_highway_Propulsion_energy,US06_highway_Braking_energy,...
    US06_highway_Net_energy,...
    US06_highway_Avg_positive_power,US06_highway_Peak_power,...
    US06_highway_Peak_tractive_force,...
    US06_highway_Idle_time]=at_the_wheels_results(US06_highway);

%creating table for 'at the wheels' result
At_the_wheels={'Propulsion Energy Wh/km';'Braking Energy Wh/km';...
    'Net Energy Wh/km';...
    'Avg. Positive Power kW';'Peak Power kW';...
    'Peak Tractive Force kN';...
    'Idle Time %'};

udds505=[UDDS_505_Propulsion_energy;UDDS_505_Braking_energy;...
    UDDS_505_Net_energy;...
    UDDS_505_Avg_positive_power;UDDS_505_Peak_power;...
    UDDS_505_Peak_tractive_force;...
    UDDS_505_Idle_time];

hwfet=[HWFET_Propulsion_energy;HWFET_Braking_energy;...
    HWFET_Net_energy;...
    HWFET_Avg_positive_power;HWFET_Peak_power;...
    HWFET_Peak_tractive_force;...
    HWFET_Idle_time];

us06_city=[US06_city_Propulsion_energy;US06_city_Braking_energy;...
    US06_city_Net_energy;...
    US06_city_Avg_positive_power;US06_city_Peak_power;...
    US06_city_Peak_tractive_force;...
    US06_city_Idle_time];

us06_hw=[US06_highway_Propulsion_energy;US06_highway_Braking_energy;...
    US06_highway_Net_energy;...
    US06_highway_Avg_positive_power;US06_highway_Peak_power;...
    US06_highway_Peak_tractive_force;...
    US06_highway_Idle_time];

weighted=[(0.29*UDDS_505_Propulsion_energy+0.12*HWFET_Propulsion_energy+...
    0.14*US06_city_Propulsion_energy+0.45*US06_highway_Propulsion_energy);...
    (0.29*UDDS_505_Braking_energy+0.12*HWFET_Braking_energy+...
    0.14*US06_city_Braking_energy+0.45*US06_highway_Braking_energy);...
    (0.29*UDDS_505_Net_energy+0.12*HWFET_Net_energy+...
    0.14*US06_city_Net_energy+0.45*US06_highway_Net_energy);...
    (0.29*UDDS_505_Avg_positive_power+0.12*HWFET_Avg_positive_power+...
    0.14*US06_city_Avg_positive_power+0.45*US06_highway_Avg_positive_power);...
    (0.29*UDDS_505_Peak_power+0.12*HWFET_Peak_power+...
    0.14*US06_city_Peak_power+0.45*US06_highway_Peak_power);...
    (0.29*UDDS_505_Peak_tractive_force+0.12*HWFET_Peak_tractive_force+...
    0.14*US06_city_Peak_tractive_force+0.45*US06_highway_Peak_tractive_force);...
    (0.29*UDDS_505_Idle_time+0.12*HWFET_Idle_time+...
    0.14*US06_city_Idle_time+0.45*US06_highway_Idle_time)];   
    
T=table(At_the_wheels,udds505,hwfet,us06_city,us06_hw,weighted)

%for average power for acceleration and gradeability requirement
vf=27.7778;%60mph in m/s
tf=11; %required 0-60mph acceleration time
grade=3.5;%in percent
grade=atand(grade/100);%conversion to degrees

%storing the results 
[Avg_power_acc,Avg_power_gradeability]=Avg_power(vf,tf,grade);

%creating table for 
At_the_wheels_results={'Average power required to meet minimum acceleration time kW';...
    'Average power required to climb 3.5% grade at 60mph at GVWR kW'};
Values=[Avg_power_acc;Avg_power_gradeability];

T2=table(At_the_wheels_results,Values)



set(groot,'defaultFigureVisible','on')

%local function for repeated calculations of 'at the wheels' energy
%consumption
function [Propulsion_energy,Braking_energy,Net_energy,...
    Avg_propulsion_power,Peak_power,Peak_tractive_force,...
    Idle_time]=at_the_wheels_results(V)
%load required variables
run('Glider_specs.m');
Cycle_time=length(V);
Cycle_distance=sum(V)/1000; %Distance covered during the cycle in km
for c=2:Cycle_time
    if V(c)>0
        if V(c)>=V(c-1) %traction
           Ft_p(c)=cr*m*g+0.5*rho*CdAf*V(c)^2+m*(V(c)-V(c-1));%tractive force
           Pt_p(c)=Ft_p(c)*V(c);%tractive power
        elseif V(c)<V(c-1) %braking
           Ft_b(c)=abs(cr*m*g+0.5*rho*CdAf*V(c)^2+m*(V(c)-V(c-1))); %braking force
           Pt_b(c)=Ft_b(c)*V(c);  %braking power
        end
    elseif V(c)==0
        T_idle(c)=1; %idle time, vehicle has zero velocity
    end
    
end
Propulsion_energy=trapz(Pt_p)/3600; %Propulsion energy Wh
Propulsion_energy=Propulsion_energy/Cycle_distance; %Propulsion energy Wh/km
Braking_energy=trapz(Pt_b)/3600; %Braking energy Wh
Braking_energy=Braking_energy/Cycle_distance; %Braking energy Wh/km
Net_energy=Propulsion_energy-Braking_energy; %Assuming the 100% of braking energy can be recovered, net energy consumption
Avg_propulsion_power=mean(Pt_p)/1000; %Average propulsion power during the cycle kW
Peak_power=max(Pt_p)/1000; %Peak power requirement of the cycle for the glider vehicle kW
Peak_tractive_force=max(Ft_p)/1000;%Peak tractive force kN
Idle_time=(sum(T_idle)/Cycle_time)*100; % Percent idle time
end

%local function for power required for min. acceleration time and
%gradeability requirement
function [Avg_power_acc,Avg_power_gradeability]=...
    Avg_power(vf,tf,grade)
run('Glider_specs.m');
%Average power for acceleration requirement
t=0:tf-1; %'tf' is the required 0-60mph time
for c=1:length(t)
    v(c)=vf*(t(c)/tf)^0.5; %"smooth acceleration" velocity profile   
end

for c=2:length(v) %following the "smooth acceleration" profile
    Ft_a(c)=cr*m*g+0.5*rho*CdAf*v(c)^2+m*(v(c)-v(c-1));
    Pt_a(c)=Ft_a(c)*v(c);
end
Avg_power_acc=mean(Pt_a/1000);%Average power required for 0-60mph in 'tf' seconds
%Average power for greadeability requirement
Ft_g=cr*GVWR*g*cosd(grade)+0.5*rho*CdAf*vf^2+GVWR*g*sind(grade);
Avg_power_gradeability=Ft_g*27.77/1000;
end
    



